### PR TITLE
Fix publishing for collapsed fieldsets

### PR DESCRIPTION
**Pull request by kjac**
When all fieldsets have collapsed, changes made to the publish settings are not saved. This PR fixes that issue.

### CODE REVIEW

**Comment by kgiszewski** [comment]
Well that looks simple enough :) I'll try it out tomorrow if possible.

**Comment by kgiszewski** [comment]
Yo... trying to replicate the issue before I test this PR and I can't seem to find an issue. Do you know the steps to reproduce?

**Comment by kjac** [comment]
Oi!

Off the top of my head...

1. Expand a fieldset and edit the publishing settings.
2. Collapse all fieldsets.
3. Save.
4. The edits to the publishing settings have been discarded.

**Comment by kgiszewski** [comment]
Ok, mixed news. I can replicate the issue this PR is intended to fix; however when applied, it doesn't seem to fix it :)

I'm taken all the usual precautions to clear caches.

**Comment by kjac** [comment]
Well... half way there, then!

I have a few related issues on an experimental feature, and I may have a fix for it. I'll have a look at it later on.

**Comment by kgiszewski** [comment]
Optimism FTW :+1:

**Comment by kjac** [comment]
Optimism indeed :) try the latest commit?

**Comment by kgiszewski** [comment]
Hmmm, now I can't seem to save a value even if the fieldset is open.

**Comment by kjac** [comment]
Hmmm? Weird. It works on my machine (tm).

I'll try to find time to work on this Sunday.

**Comment by kgiszewski** [comment]
No worries. Full disclosure, I'm attempting this on a 7.2.8 build (in case it matters).

**Comment by kjac** [comment]
@kgiszewski ok... looks like moment.js isn't loaded on 7.2. I've replicated the issue on a 7.2.6 install. I will test some more and come up with a solution.

**Comment by kgiszewski** [comment]
Is it just a matter of including moment.js? At some point evolution is inevitable but I'd like to avoid a breaking change if possible.

**Comment by kjac** [comment]
It's fixable. I've got a workaround, just have to test on 7.3 and 7.4. And
I agree, the longer we can postpone breaking backwards compatibility, the
better.

**Comment by kjac** [comment]
@kgiszewski I've tested the latest update on 7.2.6, 7.3.5 and 7.4.1... I sure hope it works on your end too :smile:

**Comment by kgiszewski** [comment]
:+1:  I'll give it a try :)

**Comment by kjac** [comment]
No rush. Enjoy your Sunday!

**Comment by kgiszewski** [comment]
Hmm, same issue. Doesn't save. I added some debugging code to make sure it's hitting the new code and it is. I'm trying to track it down now.

**Comment by kgiszewski** [comment]
Also going to try it on 7.4

**Comment by kjac** [comment]
Hmm? Sounds an awful like you haven't deployed the updated dll?

**Comment by kgiszewski** [comment]
It's updated. However everything works on 7.4. I'll have to pickup on this tomorrow to see if it's something I'm not doing right.

**Comment by kjac** [comment]
If it keeps failing I'll spin up an 7.2.8 and test it

**Comment by kgiszewski** [comment]
More testing and more bad news. Every now and again, I get this error on 7.2.8:

screen shot 2016-04-12 at 10 52 17 am

Appears to happen on a 'new' Umbraco node.

Steps to reproduce:

- Create new node
- Add an Archetype fieldset
- Don't set the dates (ensure the publishing feature is on)
- Save/Publish

**Comment by kgiszewski** [comment]
The second save and publish does not yield the error but the values don't save (dates) either. DLL verified to be in place. I'm checking to see if the values make it to the persistence piece.

**Comment by kgiszewski** [comment]
Warning, giant log entry ahead. Dumping the values that the are coming into the converter from the editor, we seem to have `null` values in the `releaseDate` and `expireDate` despite having full values in the `releaseDateModel` and `expireDateModel`. I'm going to see if there is any updates to the datepicker since 7.2.8 that fix any sort of bugs. Unrelated we've seen datepicker issues in this version.

```
2016-04-12 11:15:44,655 [49] INFO  Archetype.PropertyEditors.ArchetypePropertyEditor - [P6388/T53/D16] {
  "fieldsets": [
    {
      "properties": [
        {
          "alias": "headline",
          "value": "fasdfasdf",
          "propertyEditorAlias": "Umbraco.Textbox",
          "dataTypeId": -88,
          "dataTypeGuid": "0cc0eba1-9960-42c9-bf9b-60e150b429ae",
          "editorState": {},
          "hostContentType": null,
          "isValid": true
        },
        {
          "alias": "table",
          "value": {
            "useFirstRowAsHeader": false,
            "useLastRowAsFooter": false,
            "tableStyle": null,
            "columnStylesSelected": [
              null,
              null
            ],
            "rowStylesSelected": [
              null,
              null,
              null
            ],
            "cells": [
              [
                {
                  "value": ""
                },
                {
                  "value": ""
                }
              ],
              [
                {
                  "value": ""
                },
                {
                  "value": ""
                }
              ],
              [
                {
                  "value": ""
                },
                {
                  "value": ""
                }
              ]
            ]
          },
          "propertyEditorAlias": "Imulus.TableEditor",
          "dataTypeId": 20541,
          "dataTypeGuid": "cafd725f-e7b2-4896-9ab8-c4c569432659",
          "editorState": {},
          "hostContentType": null,
          "isValid": true
        },
        {
          "alias": "navigationName",
          "value": "",
          "propertyEditorAlias": "Umbraco.Textbox",
          "dataTypeId": -88,
          "dataTypeGuid": "0cc0eba1-9960-42c9-bf9b-60e150b429ae",
          "editorState": {},
          "hostContentType": null,
          "isValid": true
        },
        {
          "alias": "disableBackButton",
          "value": "0",
          "propertyEditorAlias": "Umbraco.TrueFalse",
          "dataTypeId": -49,
          "dataTypeGuid": "92897bc6-a5f3-4ffe-ae27-f2e7e33dda49",
          "editorState": {},
          "hostContentType": null,
          "isValid": true
        }
      ],
      "alias": "resourceTableModule",
      "disabled": false,
      "id": "7beed658-ac6a-4bfa-8296-4bda621c1ee7",
      "releaseDate": null,
      "expireDate": null,
      "collapse": false,
      "releaseDateModel": {
        "alias": "archetypeReleaseDate_5",
        "view": "datepicker",
        "value": "2016-04-13 11:15:38",
        "config": {
          "pickDate": true,
          "pickTime": true,
          "useSeconds": true,
          "format": "YYYY-MM-DD HH:mm:ss",
          "icons": {
            "time": "icon-time",
            "date": "icon-calendar",
            "up": "icon-chevron-up",
            "down": "icon-chevron-down"
          },
          "language": "en-GB"
        }
      },
      "expireDateModel": {
        "alias": "archetypeExpireDate_6",
        "view": "datepicker",
        "value": "2016-04-14 11:15:41",
        "config": {
          "pickDate": true,
          "pickTime": true,
          "useSeconds": true,
          "format": "YYYY-MM-DD HH:mm:ss",
          "icons": {
            "time": "icon-time",
            "date": "icon-calendar",
            "up": "icon-chevron-up",
            "down": "icon-chevron-down"
          },
          "language": "en-GB"
        }
      },
      "isValid": true
    }
  ]
}
2016-04-12 11:15:44,702 [49] INFO  Umbraco.Core.Publishing.PublishingStrategy - [P6388/T53/D16] Content 'asdfasdfasdfasdf' with Id '30369' has been published.
2016-04-12 11:15:44,739 [49] INFO  Archetype.PropertyEditors.ArchetypePropertyEditor - [P6388/T53/D16] {"fieldsets":[{"properties":[{"alias":"headline","value":"fasdfasdf"},{"alias":"table","value":"{\r\n  \"useFirstRowAsHeader\": false,\r\n  \"useLastRowAsFooter\": false,\r\n  \"tableStyle\": null,\r\n  \"columnStylesSelected\": [\r\n    null,\r\n    null\r\n  ],\r\n  \"rowStylesSelected\": [\r\n    null,\r\n    null,\r\n    null\r\n  ],\r\n  \"cells\": [\r\n    [\r\n      {\r\n        \"value\": \"\"\r\n      },\r\n      {\r\n        \"value\": \"\"\r\n      }\r\n    ],\r\n    [\r\n      {\r\n        \"value\": \"\"\r\n      },\r\n      {\r\n        \"value\": \"\"\r\n      }\r\n    ],\r\n    [\r\n      {\r\n        \"value\": \"\"\r\n      },\r\n      {\r\n        \"value\": \"\"\r\n      }\r\n    ]\r\n  ]\r\n}"},{"alias":"navigationName","value":null},{"alias":"disableBackButton","value":0}],"alias":"resourceTableModule","disabled":false,"id":"7beed658-ac6a-4bfa-8296-4bda621c1ee7","releaseDate":null,"expireDate":null}]}
2016-04-12 11:15:44,742 [49] INFO  Archetype.PropertyEditors.ArchetypePropertyEditor - [P6388/T53/D16] {"fieldsets":[{"properties":[{"alias":"headline","value":"fasdfasdf"},{"alias":"table","value":"{\r\n  \"useFirstRowAsHeader\": false,\r\n  \"useLastRowAsFooter\": false,\r\n  \"tableStyle\": null,\r\n  \"columnStylesSelected\": [\r\n    null,\r\n    null\r\n  ],\r\n  \"rowStylesSelected\": [\r\n    null,\r\n    null,\r\n    null\r\n  ],\r\n  \"cells\": [\r\n    [\r\n      {\r\n        \"value\": \"\"\r\n      },\r\n      {\r\n        \"value\": \"\"\r\n      }\r\n    ],\r\n    [\r\n      {\r\n        \"value\": \"\"\r\n      },\r\n      {\r\n        \"value\": \"\"\r\n      }\r\n    ],\r\n    [\r\n      {\r\n        \"value\": \"\"\r\n      },\r\n      {\r\n        \"value\": \"\"\r\n      }\r\n    ]\r\n  ]\r\n}"},{"alias":"navigationName","value":null},{"alias":"disableBackButton","value":0}],"alias":"resourceTableModule","disabled":false,"id":"7beed658-ac6a-4bfa-8296-4bda621c1ee7","releaseDate":null,"expireDate":null}]}
2016-04-12 11:15:44,748 [49] INFO  Archetype.PropertyEditors.ArchetypePropertyEditor - [P6388/T53/D16] {"fieldsets":[{"properties":[{"alias":"headline","value":"fasdfasdf"},{"alias":"table","value":"{\r\n  \"useFirstRowAsHeader\": false,\r\n  \"useLastRowAsFooter\": false,\r\n  \"tableStyle\": null,\r\n  \"columnStylesSelected\": [\r\n    null,\r\n    null\r\n  ],\r\n  \"rowStylesSelected\": [\r\n    null,\r\n    null,\r\n    null\r\n  ],\r\n  \"cells\": [\r\n    [\r\n      {\r\n        \"value\": \"\"\r\n      },\r\n      {\r\n        \"value\": \"\"\r\n      }\r\n    ],\r\n    [\r\n      {\r\n        \"value\": \"\"\r\n      },\r\n      {\r\n        \"value\": \"\"\r\n      }\r\n    ],\r\n    [\r\n      {\r\n        \"value\": \"\"\r\n      },\r\n      {\r\n        \"value\": \"\"\r\n      }\r\n    ]\r\n  ]\r\n}"},{"alias":"navigationName","value":null},{"alias":"disableBackButton","value":0}],"alias":"resourceTableModule","disabled":false,"id":"7beed658-ac6a-4bfa-8296-4bda621c1ee7","releaseDate":null,"expireDate":null}]}
2016-04-12 11:15:44,814 [49] INFO  Archetype.PropertyEditors.ArchetypePropertyEditor - [P6388/T53/D16] {"fieldsets":[{"properties":[{"alias":"headline","value":"fasdfasdf"},{"alias":"table","value":"{\r\n  \"useFirstRowAsHeader\": false,\r\n  \"useLastRowAsFooter\": false,\r\n  \"tableStyle\": null,\r\n  \"columnStylesSelected\": [\r\n    null,\r\n    null\r\n  ],\r\n  \"rowStylesSelected\": [\r\n    null,\r\n    null,\r\n    null\r\n  ],\r\n  \"cells\": [\r\n    [\r\n      {\r\n        \"value\": \"\"\r\n      },\r\n      {\r\n        \"value\": \"\"\r\n      }\r\n    ],\r\n    [\r\n      {\r\n        \"value\": \"\"\r\n      },\r\n      {\r\n        \"value\": \"\"\r\n      }\r\n    ],\r\n    [\r\n      {\r\n        \"value\": \"\"\r\n      },\r\n      {\r\n        \"value\": \"\"\r\n      }\r\n    ]\r\n  ]\r\n}"},{"alias":"navigationName","value":null},{"alias":"disableBackButton","value":0}],"alias":"resourceTableModule","disabled":false,"id":"7beed658-ac6a-4bfa-8296-4bda621c1ee7","releaseDate":null,"expireDate":null}]}
```

**Comment by kgiszewski** [comment]
This issue gave me reason to believe v7.2.8 has issues with the datepicker: http://issues.umbraco.org/issue/U4-6953

Indeed if I replace my local 7.2.8 `datetimePickerController` method with the code from 7.4.2, it works. So I'd like to declare this a core issue. Thoughts?

**Comment by kgiszewski** [comment]
I do want to point out the errors with the screenshot above still happen. Wonder if we can do a simple undefined check to fix. Also want to know if it's a thing on 7.4.2... (testing now).

**Comment by kgiszewski** [comment]
Confirmed, it happens in 7.4.2 also. Problem is it's in a core directive. @kjac any insight on where we're triggering this?

screen shot 2016-04-12 at 11 30 32 am

**Comment by kgiszewski** [comment]
Works fine after the first save/publish. Should this run at least once (maybe it does)? https://github.com/kjac/Archetype/blob/fix-publishing-for-collapsed-fieldsets/app/controllers/controller.js#L328-L341

Lots of questions, hoping to trigger some thoughts on your end.

**Comment by kjac** [comment]
Hey. What a great testing effort you've put in. And what a mess you've made
:-D

Leave it be for now. I'll spin up a 7.2.8 and take over the testing as soon
as I have time.

Awesome job tracking down things. You rock!

**Comment by kjac** [comment]
@kgiszewski I've got it reproduced on 7.2.8. Here's the short story:

The JS errors on new documents are fixable. 

The lack of saving is a timing issue - pretty much what I was trying to solve by adding an extra submit watcher.

All in all I'm going back to the drawing board. In all likelihood - specially with the core datepicker history of... well... bugs - I'm going to drop the reuse of the core datepicker and see what kinda impact that has on the code.

I'll get back to you as soon as I have something to show :)

**Comment by kgiszewski** [comment]
Cool. Absolutely no rush :)

**Comment by kgiszewski** [comment]
FYI, I released v1.12.4 today for the features ready to go. This will still be for v1.13.0 when the time comes. I created a branch for v1.12.4 but the WIP is still staged on Master for now. I didn't want to muck up the revision history with a bunch of reverts. So again, no rush.

**Comment by kjac** [comment]
Cool. I've got a bit of a family pickle I need to sort so it might be a
good week or so before I can do much.

**Comment by kjac** [comment]
@kgiszewski OK. Been digging around a bit more, and before I throw myself at coding a bunch, we should probably discuss the performance fix in #301. This is causing us some hurt in other parts of Archetype (for example #325), and is also going to make this fix cumbersome. Not impossible, just cumbersome.

Question is if rolling back #301 is something worth considering?

**Comment by Nicholas-Westby** [comment]
> Question is if rolling back #301 is something worth considering?

"Noooooooooo!" - Darth Vader / Doc Ock

http://24days.in/umbraco/2015/umbraco-zeitgeist/#archetype

archetype

That performance fix was a huge enhancement to Archetype. It made some clients very, very happy. Removing it would make many clients very, very unhappy. I personally vote to keep that fix in there (or some alternative performance fix) at all costs.

**Comment by kjac** [comment]
@Nicholas-Westby alright alright :) I've found another workaround, that might even make said clients even happier because it boosts performance a little (see the comment for 394572a).

@kgiszewski I've tested this on 7.2.8, 7.3.5 and 7.4.1 - fingers crossed it works on your end too. I'm a bit pressed for time atm due to family stuff, so I haven't had a chance to test this for nested Archetypes. Could I trouble you to do that, if you have some configured?

**Comment by kgiszewski** [comment]
@kjac, I'll test it all out. Stellar work as usual! We are under no pressure to push this before we need to. Busy weekend for me too. I'll likely hit this Monday.

**Comment by kgiszewski** [comment]
Success!

**Comment by kgiszewski** [comment]
For whatever reason, the merge is failing :(

**Comment by kgiszewski** [comment]
Github was flaking out, all merged :)

**Comment by kjac** [comment]
Whaaaa! Cool!

I'll add the member group settings in a new PR soon.

**Pull request merged**
