### PR TITLE
UI overhaul

### PR DESCRIPTION
**Pull request by kjac**
New UI as discussed in #285.

archetype ui redo 01

archetype ui redo 02

### CODE REVIEW

**Comment by kjac** [comment]
On a usability note, we may want to add an option to substitute the "add new fieldset here" buttons on the fieldsets with the "default add" button (below all the fieldsets), leaving the "default add" button as the only means of adding a new fieldset? 

I personally like the "add new fieldset here" buttons, but I suspect they may not be terribly intuitive to use for less experienced users. Dunno... it's worth thinking about, I guess.

**Comment by kjac** [comment]
Oh - and someone please test this in Firefox?

**Comment by kgiszewski** [comment]
I'm reviewing this now #h5yr.

I'm planning on releasing a beta or release candidate for others to review easier before we merge. :+1:

**Comment by kjac** [comment]
Awesome :+1:

**Comment by kgiszewski** [comment]
Ok wow. I'm impressed :+1: 

Only one thing jumped out at me at first. Notice longer doctype name wrap and get clipped:
screen shot 2015-08-19 at 8 29 25 am

**Comment by kjac** [comment]
@kgiszewski Right ... that should be fixable :) I'll update the PR soon

**Comment by kgiszewski** [comment]
RC1 release => https://www.nuget.org/packages/Archetype/1.10.0-ui-rc1

**Comment by leekelleher** [comment]
:+1: Looking good!

**Comment by kgiszewski** [comment]
Firefox 34 works fine with one exception:

screen shot 2015-08-19 at 8 57 45 am

Dates are coming back as invalid despite they are valid.

This could be a core issue though. Works fine in Chrome.

**Comment by kjac** [comment]
Updated the PR with a fix for the fieldset names.

@kgiszewski  I can't say for absolute certain, but I'd be very surprised if the changes I've made causes the validation issue you mention. Can you try the same with a build from the current tip of the master branch?

**Comment by kgiszewski** [comment]
I'd be surprised too and I don't use FF unless testing :/

**Comment by kgiszewski** [comment]
Good news. Datepicker not validating in FF is broken unrelated to your PR. Bad news is I have no idea why it won't validate.

**Comment by kjac** [comment]
It's most likely not an Archetype issue, see #288

**Comment by kgiszewski** [comment]
@kjac I'm gonna give this PR until Monday before it's merged.

Reason being is feedback and any last minute updates you want to do. :+1:

**Comment by kjac** [comment]
@kgiszewski Righty-o. I'll mull it over and maybe add a few tweaks in the weekend if I find something :) but I'm pretty happy with it as it is. The usability issue mentioned above regarding the "add" buttons should be handled in a separate PR later on, if at all.

**Pull request merged**
