### PR TITLE
Allow html in fieldset title

### PR DESCRIPTION
**Pull request by rosrosros**
This will allow us to display images af fieldset title to help the
editor when working with images

### CODE REVIEW

**Comment by Nicholas-Westby** [comment]
As another user of Archetype, I would prefer that this functionality be opt-in. For example, I very often show the value of a rich text editor property in the Archetype fieldset title. Currently, it does as I expect and converts the rich text to plain text and adds an ellipsis if the text is very long. Just a note in case this breaks that functionality (not saying it would, but just in case).

**Comment by kgiszewski** [comment]
@Nicholas-Westby I concur. 

@rosrosros I might have to reject this PR for now due to the XSS issue this might also create.

For example, I know users take data in from forms and create fieldsets. Right now, they might feel it's pretty safe because of the current implementation. But if we allow the HTML to come through, I'm thinking someone could gain access to the backoffice with some clever JS tags they might pass in.

If the developer opts this in, then I'll sleep better at night.

Open to discussion of course.

**Comment by rosrosros** [comment]
I see your points and agree with both them. 
However adding an opt-in could be a solution - where I as developer understand and accepts the risk

**Comment by kgiszewski** [comment]
Closing for now, please feel free to re-open if you can add an 'opt-in' option.

**Pull request closed without merging**
