### PR TITLE
Support publish and unpublish

### LINKED ISSUE #334: Feature request: publish/unpublish date
Archetype is great, it has replaced the tedious work of creating new "pages" every time you wanted a data entry added.
However one of the percs with the "old" system was that the editor could easily set a start and stop publish date for temp campaigns.

Right now it's pretty easy to implement your own date fields and check those, however it would be nice if there was a UI hint, or even better if it was automatically enabled/disabled.

I guess a UI hint should be fairly easy if I write my own view that checks if current date is within a date span.

### PR DESCRIPTION
**Pull request by kjac**
Fixes #334 

**Please note:** Unlike Umbraco's built-in publish and unpublish for content types, this implementation uses UTC to determine when a fieldset should be published or unpublished. Although that's a deviation from the Umbraco way of doing things, I fear we'll get flooded with support issues if we don't use UTC.

archetype-publish-6

### CODE REVIEW

**Comment by kgiszewski** [comment]
Thanks @kjac, I'm planning on checking this PR in the near future.

Re: UTC time. I think saving it as UTC is a good idea. I wonder if it's worth also display the local time (server time) as well so that editors can have visual reassurance that the time they picked is what they intended.

I'm offering that thought above without seeing the PR so I'll have more to say I'm sure.

**Comment by kjac** [comment]
@kgiszewski The way I see it, UTC should be the assurance of this. If I as an editor pick a publish date and time, I expect the fieldset to be published on that date and time. I don't care about server time, I just care about it getting published on time. Provided that my timezone is set correctly for my browser to use, the UTC conversion should ensure that things work as expected.

I don't know if you've ever played around with the built-in stuff, but it's a pain in a certain place that you can't for sure count on the publish and unpublish time. If I choose to publish at 18:00, the server will publish at 18:00 on it's local time, which could be any other hour for me.

**Comment by kgiszewski** [comment]
@kjac Amen ;) I'll review the PR before too long and see for myself :+1:

**Comment by kgiszewski** [comment]
Ok, I just review three others and this one will take quite a bit more effort to review. Possibly tomorrow or Monday. :+1:

**Comment by kjac** [comment]
:+1: no rush. If we end up merging this, I've got the member groups thing (#341) sort of ready too.

**Comment by kjac** [comment]
Hmm there's a merge conflict after the most recent PRs (well, one of mine actually...). I'll fix and update this PR.

**Comment by kjac** [comment]
Should be good to go.

**Comment by kgiszewski** [comment]
This will likely get merged this week. I wanted to test it against a 7.4.x build and a 7.2.8 build at my day job. :+1:

**Comment by kgiszewski** [comment]
Reviewing this and ran into an issue. Looks like when I upgrade to this PR locally and attempt to tick the box called `Enable Fieldset Publishing?`, it appears to work. But after I save and reload the config for that Archetype, it is unchecked still and therefore does not show on the editor side of things.

If I create a new Archetype, same thing occurs; the setting does not stick. I'm looking into it.

**Comment by kjac** [comment]
Are you running grunt and building in debug? That would explain it... It
gets me every time :-)

**Comment by kgiszewski** [comment]
I found the issue: https://github.com/imulus/Archetype/commit/715a2bf6d5d90b887fcda71f832c699c97c5c2a4

Had to do with the `dialogData` branch that fixed #342

**Comment by kjac** [comment]
Oh... Duh. Of course.

**Comment by kgiszewski** [comment]
No worries, I knew right where to look :)

**Comment by kgiszewski** [comment]
@kjac, nicely done!

Some feedback...

Rather than show the :watch: icon after is expired (I think that's the only time it shows), what do you think about showing the clock icon (as an additional icon or somewhere else) whenever anything is placed into either box (release or expiry)? Sort of a visual cue that there is something filled in to those settings (as they are collapsed most of the time).

Then when it expires, simply set the disabled to true (thus lighting up the power icon).

Don't throw anything at me if this was your previous point earlier :)

Oh and the time works as expected (re: earlier conversation about local time).

**Comment by kgiszewski** [comment]
I merged and we can discuss the timer icon as it's just a minor thing if anything at all.

BTW, :+1: on the effort and clean code #h5yr!

**Comment by kjac** [comment]
It's no problem to show both the power and the time icon alongside each
other. However I'd recommend showing both icons all the time, then, because
it looks confusing when there aren't the same number of icons on all
fieldsets.

However. The gain of doing so is solely to be able to disable expired or
not yet released fieldsets, so I'm not sure it's worth adding an extra icon
all the time just for that?

**Comment by kgiszewski** [comment]
How's about showing the icon all the time only when it's enabled in the config? So for most users, they will never see the icon unless they plan to schedule them?

**Comment by kjac** [comment]
Oh ya of course, that's a given no matter what. Just like with the power
icon.

I'll have a look at it soon :-)

**Comment by kgiszewski** [comment]
Just my 2 cents of course, but I'm ok with the way you have it.

**Pull request merged**
