### PR TITLE
Master

### PR DESCRIPTION
**Pull request by markwemekamp**
I've added a performance tweak for nested archetypes, by adding this piece of code the angularjs digest cycle for properties is called when expanding the fieldset instead of on the initial load. This fixed a serious performance problem for us.
Just see for yourself if you want to include this in the masterbranch.

### CODE REVIEW

**Comment by kgiszewski** [comment]
Awesome thank you, I'll review it soon. Any issues with datatypes such as the RTE?

**Comment by markwemekamp** [comment]
Not that I know of, I did a quick test with several datatyped including RTE and everything worked fine

**Comment by kgiszewski** [comment]
That's great news :+1: Just out of curiosity, do you have any metrics you can share? i.e. load times went from x to y. Or even non-metrics like, 'responsiveness came back'?

**Comment by markwemekamp** [comment]
We noticed that with Archetypes with 20+ rows with a sub-Archetype with more 10+ rows that the Umbraco interface froze on loading for a couple of seconds up to half a minute. I profiled the code and noticed the angularjs digest cycle took up 40% of this time. After implementing this fix, the interface loads immediately. 
I can build a test case with exact numbers if you like.

**Comment by kgiszewski** [comment]
Exact numbers aren't necessary but I might try to replicate it on my side. Thank you for the insight.

**Comment by kgiszewski** [comment]
So far so good, thanks! :+1:

**Comment by kjac** [comment]
I just tested this, and @kgiszewski is right, it works fine with both upload and image cropper, in both root and nested fieldsets. My test site is a bit dated (7.2.6 - I need to update it!)... but it should be fine. @mattbrailsford thanks for the heads up, tho' :+1:

**Pull request merged**
