### PR TITLE
Fix 323

### LINKED ISSUE #323: Group Unset When Applying Global Fieldset Options
See demo:

group

If my fieldsets have a group assigned and I click `Global Fieldset Options` then `Apply`, the dropdown containing the group is unset. I'm now hesitant to add any new groups or change any global settings, as I'm afraid that will unset all the groups I've set on my many fieldsets.

### PR DESCRIPTION
**Pull request by kjac**
This fixes #323 by introducing "live editing" of the config model in the config dialogs.

It also fixes an erroneous path in the grunt file :)

### CODE REVIEW

**Comment by kgiszewski** [comment]
Well that was fast! I'll have a look likely Monday. #h5yr

**Comment by kjac** [comment]
Cheers. Have a grand weekend!

**Comment by kgiszewski** [comment]
@kjac I haven't forgotten about this. I'm about to go on a vacation/holiday and having some time management issues :) I'll likely review this after my time off so I can respond to any issues if they crop up (not that I'm expecting any to).

**Comment by kjac** [comment]
No rush :-) have a grand ol' time!

**Comment by kgiszewski** [comment]
@kjac It all checked out :+1: 

Will likely release this with the Feb Update the week of the 15th (when I return).

**Comment by kjac** [comment]
Ooh nice with some time off. Enjoy!

**Pull request merged**
