### PR TITLE
Fix #194 once again

### LINKED ISSUE #194: RTE not working after sorting
After I discovered that you could [sort](http://our.umbraco.org/projects/backoffice-extensions/archetype/sound-off!/55264-Sort-Archetype-fieldset?p=0#comment190302) ;-) I found out that if you sort a fieldset the RTE is disabled afterwards.
rte-sort

### PR DESCRIPTION
**Pull request by kjac**
Alright... I've shamelessly stolen and adapted the current Grid implementation and it works like a charm. 

Note that I've removed the clean-up in ```$scope.sortableOptions.stop``` as there doesn't seem to be a leak of editors anymore. You can verify this by adding ```console.log($(rteClass).length)``` in ```$scope.sortableOptions.stop```.

### CODE REVIEW

**Comment by kgiszewski** [comment]
No shame in it. I'm pretty sure this repo has had many things borrowed from it. :+1: 

I'll test it out as early as today thanks!

**Comment by tomfulton** [comment]
Confirmed this fixes #194 for me in 7.3 w/Archetype 1.10.  Thanks Kenn!

**Comment by kgiszewski** [comment]
@tomfulton can you merge or do you not have access?

**Comment by kgiszewski** [comment]
We need to mark the next release to depend on 7.3.0+

**Comment by kjac** [comment]
Hey guys. I believe this is backwards compatible... at least it works on my machine in 7.2.8 :) 

No matter what, I think it would be silly to make the next release depend on 7.3+ just for handling RTE dragging. If this fix doesn't work on 7.2.x, I'd much rather implement a workaround for older versions of Umbraco than have a version dependency because of this issue.

**Comment by kgiszewski** [comment]
I can confirm it works in 7.2.8 and 7.3.0 so we can leave the dependency as-is :+1:

**Pull request merged**
