### PR TITLE
Fixes for Virtual Directories #156

### PR DESCRIPTION
**Pull request by kipusoep**
Fixes for Virtual Directories #156 

Please review the changes!

### CODE REVIEW

**Comment by kgiszewski** [comment]
Oh snap ;)

Thanks, I'll try to get this looked at probably early next week. :+1:

**Comment by kgiszewski** [comment]
Thanks!

**Comment by tomfulton** [comment]
@kipusoep Looks good from here too!  I ended up abandoning the virtual directory route as there were too many issues that kept cropping up.  In the end we setup the backoffice server to run at the root, and the front-end nodes to use virtual directories...seems to be working well!

Anyway, one note - the tilde support in `PropertyEditor` and `PreValueField` were added in later versions of Umbraco, so we should probably mark the next release with a minimum Umbraco version.  I believe they were added in 7.1.5 and 7.3.0-beta (according to the tags at least [[1]](https://github.com/umbraco/Umbraco-CMS/commit/a23fb7bc741df76376b640a4db5abe2fb92991fe) [[2]](https://github.com/umbraco/Umbraco-CMS/commit/048a8683dd1dfc623805c83096929f7a73ff164c)).

Alternatively, we might think about using relative paths instead to maintain backward compatibility, ie `../App_Plugins/Archetype/...`.  Shannon seems to think this should work fine in [this comment](http://issues.umbraco.org/issue/U4-6775#comment=67-21503).

**Comment by kgiszewski** [comment]
I just ran into an issue with the config page throwing 404. Trying to track that down.

**Comment by kgiszewski** [comment]
@tomfulton Thanks man. I think we're up to min version of 7.1.6 so far. Any other gotchas?

**Comment by kgiszewski** [comment]
I think this will fix it: https://github.com/umbraco/Umbraco-CMS/commit/048a8683dd1dfc623805c83096929f7a73ff164c as @tomfulton suggests. So maybe this will have to wait for core 7.3

**Comment by kgiszewski** [comment]
Curious why the editor doesn't break for the same reason... hmmm.

**Comment by tomfulton** [comment]
@kgiszewski Not that I can think of - as mentioned I abandoned this setup, but this looks like everything I did to get it working initially ;).

Yeah, that's the update I was thinking of and was introduced in 7.3.0-beta.  Instead of relying on that update you can try using relative paths as mentioned above...should work.

One other thing you might want to test, is make sure `debug=false` in the web.config and everything still works.  I recall some issues with ClientDependency playing nice with the virtual routes.

**Comment by tomfulton** [comment]
@kgiszewski because `[PropertyEditor]` supports the virtual paths as of 7.1.5, but `[PreValueField]` does not until 7.3.0-beta ;)

**Comment by kgiszewski** [comment]
@tomfulton Awesome for the pain you've already done on this.

So if I change to relative (`../`), I think we can forego the need for users to go to v7.3.x right?

It appears to work find with the relative path in place but I haven't actually tried with a virtual directory yet.

**Comment by tomfulton** [comment]
Yep, that's correct in theory ;)

**Comment by kgiszewski** [comment]
@tomfulton super, I'm adding [this](https://github.com/imulus/Archetype/issues/249) and I don't want to have to wait on nor depend on 7.3 :)

**Pull request merged**
