### PR TITLE
Break up options into separate dialogs

### PR DESCRIPTION
**Pull request by kgiszewski**
Works, figuring out how to prevent multiple dialogs at once.

screen shot 2015-10-07 at 4 08 17 pm

### CODE REVIEW

**Comment by kgiszewski** [comment]
@kjac @tomfulton @leekelleher @mattbrailsford If any of you gents could offer any feedback, it'd be appreciated. You don't have to clone or build, but the concept is the real thing to consider.

**Comment by jamiepollock** [comment]
@kgiszewski will the config source field still be an option? It'd be great if that was outside of the dialog setup. I've used it a couple of times when duplicating functionality slightly.

**Comment by kjac** [comment]
Looks good at first glance. I'll get back to you tomorrow :-)

**Comment by kgiszewski** [comment]
@jamiepollock Yep it'll be there, just on the developer dialog.

**Comment by kjac** [comment]
I've added a few tweaks in #298 - see PR comments for details.

**Pull request merged**
