### PR TITLE
Support upload and imagecropper datatypes

### PR DESCRIPTION
**Pull request by kjac**
Let's try this again :)

To support upload and imagecropper datatypes, all uploaded files must be registered client side in the ```fileManager``` for the containing Archetype, in order for these files to be send to the Archetype property editor's ```ConvertEditorToDb()``` method as "additional data". This is pretty much what the JS changes in this PR is all about. I've introduced an ```EditorState``` on the Archetype properties to contain any temporary editor state that needs to be sent to the server side for processing (currently it only contains the file names of the uploaded files)

On the server side, the Archetype property editor's ```ConvertEditorToDb()``` method does all the heavy lifting. It needs to identify the uploaded files (if any) for each Archetype property and send these as "additional data" to the respective datatype property editor's ```ConvertEditorToDb()``` method. 

The upload and imagecropper datatypes need to know their previous value when their values change, in order to clean up any unused files on the disk. Therefore I've introduced an ```Id``` property on the Archetype fieldset to be able to positively identify the previous property value of a property in any given fieldset (fieldset ```Id``` + property ```Alias``` yields a unique key for any property in an Archetype).

The changes to ```ArcheTypePropertyEditor``` look rather extensive in the GitHub diff tool. My apologies. It was formatted all strange (mixed spaces and tabs), and it was driving me crazy ... had to fix it, couldn't be helped :) but it's only the ```ConvertEditorToDb()``` method that's changed in this class.

There's a curious issue with the imagecropper. It's default prevalue collection contains a "focalPoint" JSON string. However, if this JSON string is sent to the imagecropper clientside, nothing works. It must be deserialized into a JSON object before it's sent to the imagecropper, and then it works like a charm. I've opted for performing this deserialization server side (in ```ArchetypeDataTypeController```) for improved re-usability, but it could just as well be performed client side.

This PR also works for nested Archetypes.

Have fun testing :)

### CODE REVIEW

**Comment by kgiszewski** [comment]
Amazing, I'll probably look at this on Monday or Tuesday. Thanks for this! #h5yr

**Comment by kgiszewski** [comment]
Ok, initial testing has been completed. The good news is the Image Cropper seems to work great. However the upload property is throwing a JS error. I'm building this against core version 7.2.6.

```TypeError: Cannot read property 'fileCount' of undefined
    at clearFiles (umbraco.controllers.js:5044)
    at initialize (umbraco.controllers.js:5054)
    at new fileUploadController (umbraco.controllers.js:5097)
    at d (angular.min.js:28)
    at Object.instantiate (angular.min.js:28)
    at $get (angular.min.js:53)
    at angular.min.js:44
    at n (angular.min.js:7)
    at k (angular.min.js:44)
    at e (angular.min.js:40)```

![screen shot 2015-07-01 at 8 19 58 am](https://cloud.githubusercontent.com/assets/4653907/8454307/4d57ac06-1fca-11e5-99c9-e1e6fdd867cc.png)

I'm gonna tinker with the core code for a bit to see if I can understand the issue.

**Comment by kgiszewski** [comment]
We can hack around this by adding: `scope.propertyForm = scope.form;` after https://github.com/imulus/Archetype/blob/master/app/directives/archetypeproperty.js#L111

Now the next error I'm seeing is: 

```
TypeError: Cannot read property 'mandatory' of undefined
    at Object.$scope.validateMandatory [as valPropertyValidator] (http://bizmag.local/umbraco/js/umbraco.controllers.js:5103:50)
    at link (http://bizmag.local/umbraco/js/umbraco.directives.js:4237:36)
    at k (http://bizmag.local/umbraco/lib/angular/1.1.5/angular.min.js:44:444)
    at e (http://bizmag.local/umbraco/lib/angular/1.1.5/angular.min.js:40:139)
    at k (http://bizmag.local/umbraco/lib/angular/1.1.5/angular.min.js:44:382)
    at e (http://bizmag.local/umbraco/lib/angular/1.1.5/angular.min.js:40:139)
    at http://bizmag.local/umbraco/lib/angular/1.1.5/angular.min.js:39:205
    at http://bizmag.local/App_Plugins/Archetype/js/archetype.js:902:49
    at http://bizmag.local/umbraco/lib/angular/1.1.5/angular.min.js:100:347
    at j.promise.then.i (http://bizmag.local/umbraco/lib/angular/1.1.5/angular.min.js:79:437) <input type="hidden" name="fileCount" ng-model="files.length" val-property-validator="validateMandatory" class="ng-isolate-scope ng-scope ng-pristine ng-valid">
```

**Comment by kgiszewski** [comment]
Success (mostly). I've had to add this under the `archetypeProperty` directive:
```
    //upload datatype hack
    scope.propertyForm = scope.form;
    scope.model.validation = {};
    scope.model.validation.mandatory = 0;
```

I've confirmed this all works with @kjac 's validation so you can still make this mandatory.
screen shot 2015-07-01 at 9 01 27 am

Gonna run this on my local machine for a few days. Please comment back here if you have any concerns about what I had to do.

**Comment by kjac** [comment]
Hey @kgiszewski ... I was just about to upgrade my test site to 7.2.6 to see what this was all about. I was working against a 7.2.1 (!).

It looks like the issue is partially from this commit: https://github.com/umbraco/Umbraco-CMS/commit/a4f7c49f50392d3f30ee97edeb4b821bf9acb261 - please note that the tags and color picker data types may also be affected.

The first part, ```scope.propertyForm = scope.form;``` looks pretty harmless in my eyes. However, explicitly resetting ```scope.model.validation``` to an empty object for all data types seems to be a potentially dangerous move. What if some other data type relies on something (else) in it's own ```.validation``` property to work?

I'd consider adding these upload property hacks specifically to the upload data type (and possibly tags and color picker if they prove to have the same issue) similar to what's already being done for MNTP in single select mode @ https://github.com/imulus/Archetype/blob/master/app/directives/archetypeproperty.js#L136. Off the top of my head I think you should be able to identify the specific data types by the ```view``` parameter in https://github.com/imulus/Archetype/blob/master/app/directives/archetypeproperty.js#L100.

...hmmm.. Am I making any sense? I'm tired :)

**Comment by kgiszewski** [comment]
Yep it all does. In fact I'm working to apply the hacks only when needed as you suggested. :+1:

**Comment by kjac** [comment]
Cool :)

**Comment by kgiszewski** [comment]
Merged! #h5yr Now go get some sleep. :)

**Comment by kjac** [comment]
:+1:

**Pull request merged**
