### PR TITLE
Fixed #368

### LINKED ISSUE #368: LabelHelpers refering to archetypeLabelService instead of archetypeCacheService
I tried using the LabelHelpers to resolve a node's name, but found out the archetypeLabelService was used instead of the archetypeCacheService, which results in an error.
PR incoming.

### PR DESCRIPTION
**Pull request by kipusoep**
Fixed #368

### CODE REVIEW

**Comment by kgiszewski** [comment]
Is there an issue to go with this?

**Comment by kipusoep** [comment]
See title ;-) Added it as description too :-)

**Comment by kgiszewski** [comment]
Ugh, sorry :) Long day :+1:

**Comment by kipusoep** [comment]
So any idea when an update will be released? :-)

**Comment by kgiszewski** [comment]
There's one PR that needs reviewed before we release. So either I need to get to it or someone else :) If I get a thumbs up from someone that it's good, I can merge and then just worry about the package/release. I may get to everything this weekend, but I can't promise. Hopefully I can get a June release out.

**Pull request merged**
