### PR TITLE
Fix for error during Archetype drags when there are rich text editors…

### PR DESCRIPTION
**Pull request by Nicholas-Westby**
… outside of Archetype: https://github.com/imulus/Archetype/issues/362

### CODE REVIEW

**Comment by kgiszewski** [comment]
Hoping to get to review this weekend, thanks!ac

**Comment by Spijkerboer** [comment]
Cool, this helped me a lot!

**Comment by kipusoep** [comment]
Works for me too, please merge :-)

**Comment by kgiszewski** [comment]
@kipusoep Your wish is my command.

**Comment by kipusoep** [comment]
:-D thanks ;-)

**Pull request merged**
