### PR TITLE
Fix save without validation

### LINKED ISSUE #151: Cannot Save (without publishing) when archetype contains errors
Hi,

Archetype appears to be preventing Umbraco from saving changes when a field in the archetype has failed validation.

E.g. you cannot save a work-in-progress page unless you complete all the mandatory fields within an archetype.

The behavior is the same if it's built-in validation (required field) or property editor specific validation (e.g. max nodes in a MNTP)

I'm on Umbraco 7.1.4 with Archetype v1.2.1-beta.

Thanks,

### PR DESCRIPTION
**Pull request by kgiszewski**
Fix #151 

Depends on:
https://github.com/umbraco/Umbraco-CMS/pull/949

### CODE REVIEW

**Comment by kgiszewski** [comment]
A discussion going on regarding the PR that would pave the way for this feature: http://issues.umbraco.org/issue/U4-7534

Input/votes would be appreciated.

**Comment by kjac** [comment]
Hey @kgiszewski ... I haven't tested this, but based on a quick code glance, couldn't you test on `args.statusMessage !== "Saving..."` or `args.statusMessage.toLowerCase().indexOf("save") == 0` instead of `args.action !== "save"` @ https://github.com/imulus/Archetype/pull/311/files#diff-32c2318424d5b011a544698c71ada331R118? Or is the `statusMessage` not passed along as part of `args`?

It's not that I disagree with your core PR at all, but by the sound of things, Shannon doesn't feel like merging it in. On top of that, using the `statusMessage` would be backwards compatible.

**Comment by kgiszewski** [comment]
@kjac, it'll likely not get merged and at last check the `statusMessage` doesn't make it to the property editor. 

This is where that break happens: https://github.com/kgiszewski/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI.Client/src/common/services/formhelper.service.js#L53

The core only passes the `args.scope` instead of the full `args`. I added the `action` to make it cleaner... meh.

If the full `args` got passed, then yes I could :) Either way a change needs to be made. Oh well, I tried :)

**Comment by kjac** [comment]
@kgiszewski ungh :( 

Yeah, you tried. I think it's a nice addition. Fingers crossed it will make it in.

**Comment by kgiszewski** [comment]
A core fix is due in `7.4.2` to possibly allow this to work.

**Comment by kgiszewski** [comment]
The core PR was accepted. Will reevaluate my PR here.

**Pull request merged**
